# Generated by Django 3.0.7 on 2023-10-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_saleitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='grand_total',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='net_amount',
            field=models.IntegerField(default=1),
        ),
    ]
