# Generated by Django 3.0.7 on 2023-11-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20231120_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='cess',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='eway',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='po',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='sgst',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='tcs',
        ),
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='veh',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='cess',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='eway',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='po',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='sgst',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='tcs',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='veh',
        ),
    ]
